In [ ]:
import geopandas as gpd
import pandas as pd
from pathlib import Path

import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from projections.modis import HDF, one_hot_encode
from projections.raster import include_rectangular_raster

In [2]:
path = Path('../Data/LandForestType/MCD12Q1.A2001001.h10v08.006.2018142183624.hdf')
hdf = HDF()
gdf = hdf.read_geopandas(path)
gdf.head()

LC_Type1  LC_Type2  LC_Type3  LC_Type4  LC_Type5  LC_Prop1_Assessment  \
0        17         0         0         0         0                  255   
1        17         0         0         0         0                  255   
2        17         0         0         0         0                  255   
3        17         0         0         0         0                  255   
4        17         0         0         0         0                  255   

   LC_Prop2_Assessment  LC_Prop3_Assessment  LC_Prop1  LC_Prop2  LC_Prop3  QC  \
0                  255                  255         3         3         3   3   
1                  255                  255         3         3         3   3   
2                  255                  255         3         3         3   3   
3                  255                  255         3         3         3   3   
4                  255                  255         3         3         3   3   

   LW                    geometry  
0   1  POINT (-85.13422 20.00000)  
1   1  POINT (-85.12979 20.00000)  
2   1  POINT (-85.12535 20.00000)  
3   1  POINT (-85.12092 20.00000)  
4   1  POINT (-85.11649 20.00000)

In [3]:
categoricals = [
    'LC_Type1', 
    'LC_Type2', 
    'LC_Type3', 
    'LC_Type4', 
    'LC_Type5', 
    'LC_Prop1', 
    'LC_Prop2', 
    'LC_Prop3', 
    'LW'
]
hdf.map_categoricals_to_attributes(gdf, categoricals)
one_hot_encode(gdf, categoricals)

In [ ]:
%%time
# Anadir buffer a gdf
xincrement = abs(gdf.loc[0, 'geometry'].bounds[1] - gdf.loc[2400, 'geometry'].bounds[1])
yincrement = abs(gdf.loc[0, 'geometry'].bounds[0] - gdf.loc[1, 'geometry'].bounds[0])
include_rectangular_raster(gdf, xincrement=xincrement, yincrement=yincrement)

In [ ]:
# ALTERNATIVA: Mover los poligonos a formato sinusoidal y calcular todo desde alli

In [ ]:
geo_df = gpd.read_file('../Shapefiles/preprocessed/all_countries_with_eth.shp')
# Filtrar poligonos segun el area del database
# use raster.get_intersection_area in each row
# Parallelize
# Join

In [5]:

gdf.head()

LC_Prop1_Assessment  LC_Prop2_Assessment  LC_Prop3_Assessment  QC  \
0                  255                  255                  255   3   
1                  255                  255                  255   3   
2                  255                  255                  255   3   
3                  255                  255                  255   3   
4                  255                  255                  255   3   

                     geometry  LC_Type1_Barren  LC_Type1_Closed Shrublands  \
0  POINT (-85.13422 20.00000)                0                           0   
1  POINT (-85.12979 20.00000)                0                           0   
2  POINT (-85.12535 20.00000)                0                           0   
3  POINT (-85.12092 20.00000)                0                           0   
4  POINT (-85.11649 20.00000)                0                           0   

   LC_Type1_Cropland/Natural Vegetation Mosaics  LC_Type1_Croplands  \
0                                             0                   0   
1                                             0                   0   
2                                             0                   0   
3                                             0                   0   
4                                             0                   0   

   LC_Type1_Deciduous Broadleaf Forests  ...  \
0                                     0  ...   
1                                     0  ...   
2                                     0  ...   
3                                     0  ...   
4                                     0  ...   

   LC_Prop1_Mixed Broadleaf/Needleleaf Forests  LC_Prop1_Open Forests  \
0                                            0                      0   
1                                            0                      0   
2                                            0                      0   
3                                            0                      0   
4                                            0                      0   

   LC_Prop1_Permanent Snow and Ice  LC_Prop1_Sparse Forests  \
0                                0                        0   
1                                0                        0   
2                                0                        0   
3                                0                        0   
4                                0                        0   

   LC_Prop1_Sparse Herbaceous  LC_Prop1_Sparse Shrublands  \
0                           0                           0   
1                           0                           0   
2                           0                           0   
3                           0                           0   
4                           0                           0   

   LC_Prop1_Water Bodies  LC_Prop1__FillValue  LC_Prop2__FillValue  \
0                      1                    0                    0   
1                      1                    0                    0   
2                      1                    0                    0   
3                      1                    0                    0   
4                      1                    0                    0   

   LC_Prop3__FillValue  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  

[5 rows x 87 columns]

In [12]:
file = SD('../Data/LandForestType/MCD12Q1.A2001001.h10v08.006.2018142183624.hdf', SDC.READ)
getmembers(file)

[('__class__', pyhdf.SD.SD),
 ('__del__',
  <bound method SD.__del__ of <pyhdf.SD.SD object at 0x7fad904e5d00>>),
 ('__delattr__',
  <method-wrapper '__delattr__' of SD object at 0x7fad904e5d00>),
 ('__dict__', {'_id': 1441793}),
 ('__dir__', <function SD.__dir__()>),
 ('__doc__',
  'The SD class implements an HDF SD interface.\n    To instantiate an SD class, call the SD() constructor.\n    To set attributes on an SD instance, call the SD.attr()\n    method to create an attribute instance, then call the methods\n    of this instance. '),
 ('__eq__', <method-wrapper '__eq__' of SD object at 0x7fad904e5d00>),
 ('__format__', <function SD.__format__(format_spec, /)>),
 ('__ge__', <method-wrapper '__ge__' of SD object at 0x7fad904e5d00>),
 ('__getattr__',
  <bound method SD.__getattr__ of <pyhdf.SD.SD object at 0x7fad904e5d00>>),
 ('__getattribute__',
  <method-wrapper '__getattribute__' of SD object at 0x7fad904e5d00>),
 ('__gt__', <method-wrapper '__gt__' of SD object at 0x7fad904e5d00>

In [13]:
file.datasets()

{'LC_Type1': (('YDim:MCD12Q1', 'XDim:MCD12Q1'), (2400, 2400), 21, 0),
 'LC_Type2': (('YDim:MCD12Q1', 'XDim:MCD12Q1'), (2400, 2400), 21, 1),
 'LC_Type3': (('YDim:MCD12Q1', 'XDim:MCD12Q1'), (2400, 2400), 21, 2),
 'LC_Type4': (('YDim:MCD12Q1', 'XDim:MCD12Q1'), (2400, 2400), 21, 3),
 'LC_Type5': (('YDim:MCD12Q1', 'XDim:MCD12Q1'), (2400, 2400), 21, 4),
 'LC_Prop1_Assessment': (('YDim:MCD12Q1', 'XDim:MCD12Q1'),
  (2400, 2400),
  21,
  5),
 'LC_Prop2_Assessment': (('YDim:MCD12Q1', 'XDim:MCD12Q1'),
  (2400, 2400),
  21,
  6),
 'LC_Prop3_Assessment': (('YDim:MCD12Q1', 'XDim:MCD12Q1'),
  (2400, 2400),
  21,
  7),
 'LC_Prop1': (('YDim:MCD12Q1', 'XDim:MCD12Q1'), (2400, 2400), 21, 8),
 'LC_Prop2': (('YDim:MCD12Q1', 'XDim:MCD12Q1'), (2400, 2400), 21, 9),
 'LC_Prop3': (('YDim:MCD12Q1', 'XDim:MCD12Q1'), (2400, 2400), 21, 10),
 'QC': (('YDim:MCD12Q1', 'XDim:MCD12Q1'), (2400, 2400), 21, 11),
 'LW': (('YDim:MCD12Q1', 'XDim:MCD12Q1'), (2400, 2400), 21, 12)}

In [14]:
file.select('LC_Prop1_Assessment')[:]

array([[255, 255, 255, ...,  97,  97,  95],
       [255, 255, 255, ...,  95,  97,  94],
       [255, 255, 255, ...,  93,  94,  98],
       ...,
       [ 91,  94,  96, ...,  99,  99,  99],
       [ 89,  89,  96, ...,  99,  99,  99],
       [ 95, 255, 255, ...,  99,  99,  99]], dtype=uint8)

In [15]:
sds_obj = file.select('LC_Prop1_Assessment')
arr = sds_obj.get()
print(arr.shape)
print(np.unique(arr))
arr

(2400, 2400)
[  1   2   4   5   6   7   8  13  20  34  35  36  37  38  39  40  41  42
  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60
  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
  97  98  99 255]


array([[255, 255, 255, ...,  97,  97,  95],
       [255, 255, 255, ...,  95,  97,  94],
       [255, 255, 255, ...,  93,  94,  98],
       ...,
       [ 91,  94,  96, ...,  99,  99,  99],
       [ 89,  89,  96, ...,  99,  99,  99],
       [ 95, 255, 255, ...,  99,  99,  99]], dtype=uint8)

In [16]:
for ds_name in file.datasets().keys():
    sds_obj = file.select(ds_name)
    attrs = sds_obj.attributes()
    print(f"Channel name: {ds_name}. Attributes:\n\t", ",\n\t".join(attrs.keys()), "\n")

Channel name: LC_Type1. Attributes:
	 long_name,
	Evergreen Needleleaf Forests,
	Evergreen Broadleaf Forests,
	Deciduous Needleleaf Forests,
	Deciduous Broadleaf Forests,
	Mixed Forests,
	Closed Shrublands,
	Open Shrublands,
	Woody Savannas,
	Savannas,
	Grasslands,
	Permanent Wetlands,
	Croplands,
	Urban and Built-up Lands,
	Cropland/Natural Vegetation Mosaics,
	Permanent Snow and Ice,
	Barren,
	Water Bodies,
	Unclassified,
	valid_range,
	_FillValue 

Channel name: LC_Type2. Attributes:
	 long_name,
	Water Bodies,
	Evergreen Needleleaf Forests,
	Evergreen Broadleaf Forests,
	Deciduous Needleleaf Forests,
	Deciduous Broadleaf Forests,
	Mixed Forests,
	Closed Shrublands,
	Open Shrublands,
	Woody Savannas,
	Savannas,
	Grasslands,
	Permanent Wetlands,
	Croplands,
	Urban and Built-up Lands,
	Cropland/Natural Vegetation Mosaics,
	Barren,
	Unclassified,
	valid_range,
	_FillValue 

Channel name: LC_Type3. Attributes:
	 long_name,
	Water Bodies,
	Grasslands,
	Shrublands,
	Broadleaf Croplands,
	

In [43]:
sds_obj = file.select('LC_Type4')
arr = sds_obj.get()
arr

array([[  0,   0,   0, ...,   6,   6,   6],
       [  0,   0,   0, ...,   6,   6,   6],
       [  0,   0,   0, ...,   6,   6,   6],
       ...,
       [  2,   2,   2, ...,   2,   2,   2],
       [  2,   2,   2, ...,   2,   2,   2],
       [  2, 255, 255, ...,   2,   2,   2]], dtype=uint8)

In [42]:
arr = np.array([[1, 2, 3] , [4, 5, 6]])
print(arr)
arr.reshape(-1)

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [40]:
np.repeat(arr[0], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [48]:
PX = 463.312716525
ULY = 10007554.677
ULX = -20015109.354
h = 10
v = 8
grid_size = arr.shape[0]


def get_grid_ulc(h, v):
    grid_uly = ULY - v * PX * grid_size
    grid_ulx = ULX + h * PX * grid_size
    return grid_ulx, grid_uly


def get_grid_lat(grid_uly):
    return np.arange(grid_uly + PX * grid_size, grid_uly, -PX)
 
    
def get_grid_lon(grid_ulx):
    return np.arange(grid_ulx, grid_ulx + PX * grid_size, PX)


grid_ulx, grid_uly = get_grid_ulc(h, v)
grid_lat = get_grid_lat(grid_uly)
grid_lon = get_grid_lat(grid_ulx)
lons = np.tile(grid_lon, grid_size)
lats = np.repeat(grid_lat, grid_size)

In [49]:
len(lats), len(lons), len(arr.reshape(-1))

(5760000, 5760000, 5760000)

In [ ]:
%%time
df = pd.DataFrame({'lat': lats, 'lon': lons, 'value': arr.reshape(-1)})
gdf = gpd.GeoDataFrame({'value': arr.reshape(-1), 'geometry': geometry},
                      crs="+proj=sinu +a=6371007.181 +b=6371007.181 +units=m")
gdf.head()

In [55]:
%%time
geometry = [Point(lat, lon) for lat in lats for lon in lons]

KeyboardInterrupt: 

In [60]:
%%time
gdf = gpd.GeoDataFrame({'value': arr.reshape(-1)},
                       geometry=gpd.points_from_xy(lats, lons),
                      crs=)
gdf = gdf.to_crs(4326)
gdf.head()

CPU times: user 13.2 s, sys: 596 ms, total: 13.8 s
Wall time: 13.8 s


value                    geometry
0      0  POINT (58.47609 -70.00000)
1      0  POINT (58.48777 -70.00417)
2      0  POINT (58.49947 -70.00833)
3      0  POINT (58.51116 -70.01250)
4      0  POINT (58.52286 -70.01667)

In [61]:

geo_df.head()

id GID_0 portion  \
0  ESP__GUANCHE   ESP    None   
1   ESP__JEBALA   ESP    None   
2      ESP__RIF   ESP    None   
3  GHA__ADANGME   GHA    None   
4    GHA__ADELE   GHA    None   

                                            geometry  
0  MULTIPOLYGON (((-17.89487 27.78681, -17.89514 ...  
1  MULTIPOLYGON (((-5.37708 35.91704, -5.37708 35...  
2  MULTIPOLYGON (((-2.92593 35.29208, -2.92708 35...  
3  MULTIPOLYGON (((0.69465 5.77336, 0.69328 5.775...  
4  POLYGON ((0.45975 8.06680, 0.46512 8.07837, 0....

In [71]:
from shapely.geometry import Polygon
x, y, _, _ = gdf.iloc[0, -1].bounds
increment_lon = gdf.iloc[0,-1].bounds[1] - gdf.iloc[1,-1].bounds[1]
increment_lat = abs(gdf.iloc[0,-1].bounds[0] - gdf.iloc[1,-1].bounds[0])
pol = Polygon([
    (x - increment_lon, y - increment_lat), 
    (x + increment_lon, y - increment_lat), 
    (x + increment_lon, y + increment_lat), 
    (x - increment_lon, y + increment_lat)
])

In [67]:
gdf.iloc[0,-1].bounds[1] - gdf.iloc[1,-1].bounds[1]

0.004166666666264973

In [65]:
gdf.iloc[0,-1].bounds[0] - gdf.iloc[1,-1].bounds[0]

-0.01168614036338056

In [62]:
geo_df[geo_df['GID_0']=='VEN']

id GID_0 portion  \
48880    VEN.1.1_1   VEN    None   
48881    VEN.1.2_1   VEN    None   
48882    VEN.1.3_1   VEN    None   
48883    VEN.1.4_1   VEN    None   
48884    VEN.1.5_1   VEN    None   
...            ...   ...     ...   
102905  VEN.10.1_1   VEN      74   
102906  VEN.10.1_1   VEN      75   
102907  VEN.10.1_1   VEN      76   
102908  VEN.10.1_1   VEN      77   
102909  VEN.10.1_1   VEN      78   

                                                 geometry  
48880   POLYGON ((-63.37228 2.21171, -63.38110 2.20705...  
48881   POLYGON ((-65.62041 2.73716, -65.62035 2.73668...  
48882   POLYGON ((-66.94093 5.64498, -67.01332 5.58293...  
48883   POLYGON ((-67.84909 5.29383, -67.80544 5.30084...  
48884   POLYGON ((-66.56641 4.86244, -66.63248 4.89293...  
...                                                   ...  
102905  POLYGON ((-63.13403 11.34708, -63.13403 11.346...  
102906  POLYGON ((-65.38458 10.99958, -65.38458 10.999...  
102907  POLYGON ((-65.30791 10.98681, -65.30791 10.986...  
102908  POLYGON ((-65.41847 10.97708, -65.41847 10.976...  
102909  POLYGON ((-65.42931 10.97208, -65.42931 10.971...  

[416 rows x 4 columns]

(5760000,)

In [ ]:
import geopandas as gpd
gdf = gpd.GeoDataFrame(arr)

In [25]:
2400/180

13.333333333333334

In [16]:
sds_obj.attributes()

{'long_name': 'Land_Cover_Type_1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
 'Evergreen Needleleaf Forests': 1,
 'Evergreen Broadleaf Forests': 2,
 'Deciduous Needleleaf Forests': 3,
 'Deciduous Broadleaf Forests': 4,
 'Mixed Forests': 5,
 'Closed Shrublands': 6,
 'Open Shrublands': 7,
 'Woody Savannas': 8,
 'Savannas': 9,
 'Grasslands': 10,
 'Permanent Wetlands': 11,
 'Croplands': 12,
 'Urban and Built-up Lands': 13,
 'Cropland/Natural Vegetation Mosaics': 14,
 'Permanent Snow and Ice': 15,
 'Barren': 16,
 'Water Bodies': 17,
 'Unclassified': 255,
 'valid_range': [1, 17],
 '_FillValue': 255}

In [22]:
sds_obj.getcal()

HDF4Error: getcal (134): Cannot find or get an attribute

In [15]:
getmembers(sds_obj)

[('_SDS__buildStartCountStride',
  <bound method SDS.__buildStartCountStride of <pyhdf.SD.SDS object at 0x7ffb0003fc10>>),
 ('__class__', pyhdf.SD.SDS),
 ('__del__',
  <bound method SDS.__del__ of <pyhdf.SD.SDS object at 0x7ffb0003fc10>>),
 ('__delattr__',
  <method-wrapper '__delattr__' of SDS object at 0x7ffb0003fc10>),
 ('__dict__', {'_sd': <pyhdf.SD.SD at 0x7ffb20490460>, '_id': 262144}),
 ('__dir__', <function SDS.__dir__()>),
 ('__doc__',
  'The SDS class implements an HDF dataset object.\n    To create an SDS instance, call the create() or select()\n    methods of the SD class. To set attributes on an SDS instance,\n    call the SDS.attr() method to create an attribute instance,\n    then call the methods of this instance. Attributes can also be\n    set using the "dot notation". '),
 ('__eq__', <method-wrapper '__eq__' of SDS object at 0x7ffb0003fc10>),
 ('__format__', <function SDS.__format__(format_spec, /)>),
 ('__ge__', <method-wrapper '__ge__' of SDS object at 0x7ffb0003fc

In [10]:
sds_obj.attributes()

{'long_name': 'Land_Cover_Type_1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
 'Evergreen Needleleaf Forests': 1,
 'Evergreen Broadleaf Forests': 2,
 'Deciduous Needleleaf Forests': 3,
 'Deciduous Broadleaf Forests': 4,
 'Mixed Forests': 5,
 'Closed Shrublands': 6,
 'Open Shrublands': 7,
 'Woody Savannas': 8,
 'Savannas': 9,
 'Grasslands': 10,
 'Permanent Wetlands': 11,
 'Croplands': 12,
 'Urban and Built-up Lands': 13,
 'Cropland/Natural Vegetation Mosaics': 14,
 'Permanent Snow and Ice': 15,
 'Barren': 16,
 'Water Bodies': 17,
 'Unclassified': 255,
 'valid_range': [1, 17],
 '_FillValue': 255}